export const GET_PLAYLIST = {
  REQUEST: 'GET_PLAYLIST_REQUEST',
  SUCCESS: 'GET_PLAYLIST_SUCCESS',
  FAILURE: 'GET_PLAYLIST_FAILURE',
};

export const ADD_PLAYLIST = {
  REQUEST: 'ADD_PLAYLIST_REQUEST',
  SUCCESS: 'ADD_PLAYLIST_SUCCESS',
  FAILURE: 'ADD_PLAYLIST_FAILURE',
};

export const UPDATE_PLAYLIST = {
  REQUEST: 'UPDATE_PLAYLIST_REQUEST',
  SUCCESS: 'UPDATE_PLAYLIST_SUCCESS',
  FAILURE: 'UPDATE_PLAYLIST_FAILURE',
};

export const DELETE_PLAYLIST = {
  REQUEST: 'DELETE_PLAYLIST_REQUEST',
  SUCCESS: 'DELETE_PLAYLIST_SUCCESS',
  FAILURE: 'DELETE_PLAYLIST_FAILURE',
};
export const STORE_PLAYLIST = {
  REQUEST: 'STORE_PLAYLIST_REQUEST',
  SUCCESS: 'STORE_PLAYLIST_SUCCESS',
  FAILURE: 'STORE_PLAYLIST_FAILURE',
};
