export const GET_ALL_RECITATIONS = {
  REQUEST: 'GET_ALL_RECITATIONS_REQUEST',
  SUCCESS: 'GET_ALL_RECITATIONS_SUCCESS',
  FAILURE: 'GET_ALL_RECITATIONS_FAILURE',
};

export const GET_IMAGE_LIST = {
  REQUEST: 'GET_IMAGE_LIST_REQUEST',
  SUCCESS: 'GET_IMAGE_LIST_SUCCESS',
  FAILURE: 'GET_IMAGE_LIST_FAILURE',
};
