export const GET_SALAH_TIMINGS = {
  REQUEST: 'GET_SALAH_TIMINGS_REQUEST',
  SUCCESS: 'GET_SALAH_TIMINGS_SUCCESS',
  FAILURE: 'GET_SALAH_TIMINGS_FAILURE',
};

export const GET_HIJRI_MONTH = 'GET_HIJRI_MONTH';
