export const GET_ALL_COUNTRIES = {
  REQUEST: 'GET_ALL_COUNTRIES_REQUEST',
  SUCCESS: 'GET_ALL_COUNTRIES_SUCCESS',
  FAILURE: 'GET_ALL_COUNTRIES_FAILURE',
};

export const GET_CITIES_OF_COUNTRY = {
  REQUEST: 'GET_CITIES_OF_COUNTRY_REQUEST',
  SUCCESS: 'GET_CITIES_OF_COUNTRY_SUCCESS',
  FAILURE: 'GET_CITIES_OF_COUNTRY_FAILURE',
};

export const SET_USER_CITY = 'SET_USER_CITY';
export const SET_USER_COUNTRY = 'SET_USER_COUNTRY';
